trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '17'
  artifactName: 'api.jar'

steps:

  # 1) Instalar Java 17
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '17'
      architecture: 'x64'

  # 2) Build com Maven
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: false

  # 3) Copiar JAR criado para a pasta de artefatos
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/target'
      Contents: '*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # 4) Publicar artefato para o Release
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
